/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    ToDo: (() => {
      const tableId = new TableId("", "ToDo");
      return defineComponent(
        world,
        {
          done: RecsType.Boolean,
          owner: RecsType.String,
          content: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Challenge: (() => {
      const tableId = new TableId("", "Challenge");
      return defineComponent(
        world,
        {
          cid: RecsType.String,
          assets: RecsType.StringArray,
          status: RecsType.Boolean,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Asset: (() => {
      const tableId = new TableId("", "Asset");
      return defineComponent(
        world,
        {
          count: RecsType.BigInt,
          cid: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
