// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { ToDo, ToDoData, ToDoTableId } from "./tables/ToDo.sol";
import { Challenge, ChallengeData, ChallengeTableId } from "./tables/Challenge.sol";
import { Asset, AssetData, AssetTableId } from "./tables/Asset.sol";
